baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'hugo-PaperMod'
title = '虚空遁地猪qwq'
logo = "img/icon-32.png"
svgFavicon = "/fac.svg"
[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true